### ISSUE TITLE
divide by zero encountered in double scalar

### ISSUE THREAD

**Issue by mycarta** [partofthething/ace#10]
Hi there.
I am able to run the Wang example without problems. 
However, when I try to adapt to use with my own data I get an error message, attached below:
![divide](https://user-images.githubusercontent.com/7424763/30178960-0b75ce66-93c8-11e7-912d-ffddecadcb7b.png)

Do you know what might be causing this? I am including my data to allow you to try and replicate the issue. I realize it is not a lot of data points but I suspect this has not to do with the issue.

[data_final.txt](https://github.com/partofthething/ace/files/1285768/data_final.txt)

**Comment by partofthething** [comment]
Hi. Those kinds of warnings usually show up when there's a  NaN or something in one of the underlying numpy modules. I ran your problem and got the same result. I tried again changing the `x` variable to a list of numpy arrays and re-ran and it seemed to work. That's pretty fragile behavior so I'll look to fix it. 

Here's what the transforms of your data look like: 

![image](https://user-images.githubusercontent.com/5360219/36950048-6433d26e-1fa5-11e8-9b71-25dff6c0e170.png)

**Comment by partofthething** [comment]
Here's a complete example using your data of how I got that plot:

```python
import numpy as np

hunt = np.loadtxt('data_final.txt', skiprows=1)
hunt = list(zip(*hunt))
x = [np.array(xi) for xi in hunt[:4]]
y = np.array(hunt[4])

from ace import model
myace = model.Model()
myace.build_model_from_xy(x, y)

from ace import ace 
ace.plot_transforms(myace.ace)
```

**Comment by mycarta** [comment]
great, thank you!

**Comment by partofthething** [comment]
Aha, I got to the bottom of the issue here. Sometimes the denominator in `ace.smoother.BasicFixedSpanSmoother._compute_cross_validated_residual_here` is zero, which causes this. If I just avoid the NaN and pass to next iteration, it behaves much better. I'll push a more robust fix soon.

**Comment by partofthething** [comment]
I updated the code in 1593a49f3c2e84551 and it's more robust. Your initial code works with this now. Transforms are a bit nicer as well: 
![ace_transforms](https://user-images.githubusercontent.com/5360219/52602345-1e5c4600-2e17-11e9-81e2-23fb257050a9.png)

**Comment by mycarta** [comment]
Hi there. I re-installed ACE (tried both using pip and directly from source), but I am still getting the problem, ad result looks as before. IS there anything I am missing?
![image](https://user-images.githubusercontent.com/7424763/56967548-a7ce0b00-6b1e-11e9-8e57-53cd59e6042d.png)

**Comment by partofthething** [comment]
I neglected to do a full release so pip wouldn't have the code. But your "from source" install should have worked. Your transforms look like they did originally still. I'll re-verify with the new code and try to push it up to pip. Sorry about that.

**Comment by partofthething** [comment]
Ok I confirmed again that the code you posted above "works for me" on 0.3.2 which I just pushed to PyPI: https://pypi.org/project/ace/0.3.2/ 
Can you try it and let me know?

**Comment by mycarta** [comment]
Thanks Nick

I am now indeed getting the expected result (same as yours), this is great!

![image](https://user-images.githubusercontent.com/7424763/57149833-dc91ca80-6d89-11e9-96d1-e530dca12293.png)

Minor thing, still getting the error:
> C:\ProgramData\Anaconda\envs\py36\lib\site-packages\ace\smoother.py:310: RuntimeWarning: invalid value encountered in double_scalars
  self._variance_in_window)

**Comment by partofthething** [comment]
Excellent. 

I'll try to clean up that RuntimeWarning as a separate issue.
